In [1]:
import numpy as np

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [11]:
np.random.randint(0, 10, size=10)

array([4, 8, 3, 9, 6, 4, 4, 1, 3, 2])

In [14]:
rng = np.random.default_rng(seed=21221)

In [15]:
rng.random(20)

array([0.86318653, 0.89940288, 0.39362591, 0.31338045, 0.01873723,
       0.13049891, 0.77831241, 0.0176273 , 0.02013775, 0.45411026,
       0.22684229, 0.45133444, 0.88234635, 0.55249768, 0.18655768,
       0.20468182, 0.66505906, 0.55659963, 0.65388868, 0.25177418])

In [17]:
np.diag([1,3,4,5])

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [20]:
z = np.eye(10, k=4)

In [23]:
np.diag(z, k=4)

array([1., 1., 1., 1., 1., 1.])

In [30]:
z[0:4, 0:8]

array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
np.full((8,3), 'sahar')

array([['sahar', 'sahar', 'sahar'],
       ['sahar', 'sahar', 'sahar'],
       ['sahar', 'sahar', 'sahar'],
       ['sahar', 'sahar', 'sahar'],
       ['sahar', 'sahar', 'sahar'],
       ['sahar', 'sahar', 'sahar'],
       ['sahar', 'sahar', 'sahar'],
       ['sahar', 'sahar', 'sahar']], dtype='<U5')

In [33]:
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [39]:
x = np.full((3,4), [99, 98, 99, 99], dtype='i4')

In [42]:
x

array([[99, 98, 99, 99],
       [99, 98, 99, 99],
       [99, 98, 99, 99]], dtype=int32)

In [40]:
x.flatten()

array([99, 98, 99, 99, 99, 98, 99, 99, 99, 98, 99, 99], dtype=int32)

In [41]:
x.ravel()

array([99, 98, 99, 99, 99, 98, 99, 99, 99, 98, 99, 99], dtype=int32)