In [1]:
import numpy as np

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.random.randint(12, size=20).reshape(4,-1)

array([[ 4,  0,  7,  7,  9],
       [ 0,  4,  6,  3,  7],
       [ 1,  3,  9,  8,  6],
       [ 8,  6, 10,  8,  2]])